---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - role: repos
    - role: cloud
    - role: ntp
    - role: kernel-params
    - role: jenkins
    - role: cleanup
